### ISSUE TITLE
Where is the module 'worker_threads'?

### ISSUE THREAD

**Issue by ilyp** [watson/worker-threads-pool#2]

**Comment by watson** [comment]
The `worker_threads` module is a new core module available in Node.js 10.5.0. It's still experimental, so you need to run Node with the `--experimental-worker` flag, eg:

```
node --experimental-worker app.js
```

**Comment by watson** [comment]
Here's the docs: https://nodejs.org/api/worker_threads.html

**Comment by ilyp** [comment]
Thank you
